# Generated by Django 2.0 on 2019-12-11 12:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='comment',
            managers=[
                ('post_comments', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='comment_like',
            managers=[
                ('comment_likes', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='post',
            managers=[
                ('user_posts', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='post_like',
            managers=[
                ('post_likes', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterField(
            model_name='subscription',
            name='userToId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
