# Generated by Django 2.0 on 2019-12-11 12:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20191211_1200'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='subscription',
            managers=[
                ('user_saved', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterField(
            model_name='post_saved',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_saved', to=settings.AUTH_USER_MODEL),
        ),
    ]
