# Generated by Django 2.0 on 2019-12-11 12:44

from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20191211_1243'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='post_saved',
            managers=[
                ('user_saved', django.db.models.manager.Manager()),
            ],
        ),
    ]
