# Generated by Django 2.2.8 on 2019-12-23 11:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0003_post_liked_by'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='postsaved',
            managers=[
                ('post_saved', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterField(
            model_name='postsaved',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='post', to='core.Post'),
        ),
        migrations.AlterField(
            model_name='postsaved',
            name='saved_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saved_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='postsaved',
            unique_together={('saved_by', 'post')},
        ),
    ]
