# Generated by Django 2.0 on 2019-12-11 12:47

from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20191211_1244'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='subscription',
            managers=[
                ('user_subscriptions', django.db.models.manager.Manager()),
            ],
        ),
    ]
