# Generated by Django 2.2.8 on 2019-12-23 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20191223_1140'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='reply_to',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
