# Generated by Django 2.0 on 2019-12-11 12:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0005_auto_20191211_1247'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommentLike',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_by', models.IntegerField()),
                ('comment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comment_likes', to='core.Comment')),
            ],
            options={
                'verbose_name': 'Comment_like',
                'verbose_name_plural': 'Comment_likes',
            },
            managers=[
                ('comment_likes', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='PostLike',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_by', models.IntegerField()),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='post_likes', to='core.Post')),
            ],
            options={
                'verbose_name': 'Post_Like',
                'verbose_name_plural': 'Post_likes',
            },
            managers=[
                ('post_likes', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='PostSaved',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_saved', to=settings.AUTH_USER_MODEL)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='post_saved', to='core.Post')),
            ],
            options={
                'verbose_name': 'Post_saved',
                'verbose_name_plural': 'Post_saved',
            },
            managers=[
                ('user_saved', django.db.models.manager.Manager()),
            ],
        ),
        migrations.RemoveField(
            model_name='comment_like',
            name='comment',
        ),
        migrations.RemoveField(
            model_name='post_like',
            name='post',
        ),
        migrations.RemoveField(
            model_name='post_saved',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='post_saved',
            name='post',
        ),
        migrations.DeleteModel(
            name='Comment_like',
        ),
        migrations.DeleteModel(
            name='Post_like',
        ),
        migrations.DeleteModel(
            name='Post_saved',
        ),
    ]
