# Generated by Django 2.2.8 on 2019-12-23 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20191223_1500'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='content',
            field=models.TextField(default='', max_length=1000),
        ),
    ]
