# Generated by Django 2.0 on 2019-12-11 15:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0006_auto_20191211_1258'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('msg', models.TextField(null=True)),
                ('toUSer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='users_notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Notification',
                'verbose_name_plural': 'Notifications',
            },
            managers=[
                ('notifications', django.db.models.manager.Manager()),
            ],
        ),
        migrations.RenameField(
            model_name='subscription',
            old_name='userToId',
            new_name='userTo',
        ),
    ]
