# Generated by Django 2.2.8 on 2019-12-21 11:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_auto_20191211_1535'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='commentlike',
            options={'verbose_name': 'CommentLike', 'verbose_name_plural': 'CommentLikes'},
        ),
        migrations.AlterModelOptions(
            name='postlike',
            options={'verbose_name': 'PostLike', 'verbose_name_plural': 'PostLikes'},
        ),
        migrations.AlterModelOptions(
            name='postsaved',
            options={'verbose_name': 'PostSaved', 'verbose_name_plural': 'PostSaved'},
        ),
    ]
