# Generated by Django 2.0 on 2019-12-11 08:34

from django.db import migrations, models
import utils.upload
import utils.validators


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20191211_0223'),
    ]

    operations = [
        migrations.AddField(
            model_name='mainuser',
            name='is_deleted',
            field=models.BooleanField(default=0),
        ),
        migrations.AlterField(
            model_name='profile',
            name='avatar',
            field=models.FileField(blank=True, null=True, upload_to=utils.upload.document_path, validators=[utils.validators.validate_file_size, utils.validators.validate_extension]),
        ),
    ]
